# Generated by Django 5.1.3 on 2024-11-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='data_file',
            field=models.FileField(blank=True, upload_to='feedback_files/'),
        ),
    ]
