# Generated by Django 5.1.3 on 2024-11-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='average_marks',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, editable=False, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='percentage',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='remarks',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='total_marks',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
